[package]
name = "clickhouse-query"
version = "0.1.1"
edition = "2021"

[dependencies]
actix-web = "3"
clickhouse = "0.4.0"
log = "0.4.14"
tracing = "0.1.29"
tracing-subscriber = "0.3.1"

[dependencies.serde]
version = "1.0.136"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.79"
